### ISSUE TITLE
Error in adding Player

### ISSUE THREAD

**Issue by santhoshraj123** [kaltura/player-sdk-native-ios#142] opened 2016-03-28 13:23 UTC
Just integrated Kaltura Native Player with same view controller and if run the app it shows black screen with No Player created.

Kindly help me 
:Error:: -[KPlayerFactory addPlayerToController:] (line:40)
NO PLAYER CREATED

**Comment by kaltura-hooks** [comment] 2016-03-28 13:34
Hi @santhoshraj123,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by santhoshraj123** [comment] 2016-04-04 10:57
Hi Eliza custom control when i change in KMC its not reflecting in app. the thing is only button control i am able to see but the volume controll,play ,pause color are not reflecting in app.
![screen shot 2016-04-04 at 4 24 33 pm](https://cloud.githubusercontent.com/assets/827096/14245889/022d4a54-fa82-11e5-9ba9-385dcc362d8f.png)

This screen skin unable to see in app.any configuration need to add in code.

**Comment by ElizaSapir** [comment] 2016-04-04 11:09
Hey @santhoshraj123 ,

Can you try to remove the app and install it again?
Let me know if it solves the issue... i think you activated the cache on config object, this is the reason for no changes on your skin.

Best,

Eliza

**Comment by santhoshraj123** [comment] 2016-04-04 11:15
Hi ,

I deleted the app from mobile and again i installed the app green color button came but the bottom play,pause blue color not refelecting in app

**Comment by ElizaSapir** [comment] 2016-04-04 11:33
strange... give it 30m try again to remove an install since when you update UI kaltura servers has cache too and it take time to be refreshed.

If the issues is still reproducible, we will open internal issue and will resolve it.

Thanks!

**Comment by santhoshraj123** [comment] 2016-04-04 12:07
Sure .Once Kaltura cache refresh please let me know.so that i can do further process

**Comment by santhoshraj123** [comment] 2016-04-05 05:33
Hi Eliza 
any updates on this?

**Comment by ElizaSapir** [comment] 2016-04-05 08:04
@santhoshraj123,

Did you check it today? dont forget to remove the app first.

Thanks

**Comment by santhoshraj123** [comment] 2016-04-05 11:54
@ElizaSapir
i have removed and installed the same app again still the changes are not reflected in the native app

**Comment by ElizaSapir** [comment] 2016-04-05 12:42
@santhoshraj123 ,

I reopened the issue, and took it as an internal issue on our side.
The moment it resolved I will let you know by updating this issue.

Best,
Eliza

**Comment by santhoshraj123** [comment] 2016-04-06 14:42
Hi Eliza,
I have another query how kaltura is playing a videos.
my understanding is using AVPlayer the videos are playing in native iOS app.or using HTML 5 Video player the videos are playing in native app iOS .Please correct me which is correct.and what type of adverstiment it will support.

Please reply asap

**Comment by ElizaSapir** [comment] 2016-04-06 17:56
Hey @santhoshraj123,

Please see our player's architecture doc:
https://github.com/kaltura/player-sdk-native-ios/wiki/Technical-architecture

As you can see we have 2 layers for every platform.
1. webview - which is cross platform, works for iOS/ Android/ Web/ Flash and more
2. native platform engine
For iOS - we of course use AVPlayer.

Best,
Eliza

**Comment by santhoshraj123** [comment] 2016-04-06 18:42
Hi @ElizaSapir  As a developer how can we know which layer  we are playing the video.from my understanding using html5 we are playing the video in mobile apps in iOS. using web view we are hitting the url  right .then how can we use AV Player to play video

**Comment by ElizaSapir** [comment] 2016-04-07 07:38
When using iOS Kaltura Player SDK, AVPlayer is the engine which will play the content.

Best,
Eliza

**Closed** 2016-05-25 08:23 UTC

**Comment by ibrahima0404** [comment] 2019-03-17 19:54
> Just integrated Kaltura Native Player with same view controller and if run the app it shows black screen with No Player created.
> 
> Kindly help me
> :Error:: -KPlayerFactory addPlayerToController:
> NO PLAYER CREATED

@ElizaSapir I see you closed this issue but i don't see the solution to solve the issue. Can you give more details and how to solve this please.
