### ISSUE TITLE
KPIMAPlayerViewController adsLoadError not surfacing to player

### ISSUE THREAD

**Issue by piterwilson** [kaltura/player-sdk-native-ios#194] opened 2016-08-01 09:55 UTC
I'm having trouble because i can't get an error callback from the Kaltura player in the event adsLoadError (kaltura 2.4)

```
2016-08-01 11:44:36.808 [5464:127765] ::Error:: -[KPIMAPlayerViewController adsLoader:failedWithErrorData:] (line:176) 
2016-08-01 11:44:36.912 [5464:127765] -[NSNull length]: unrecognized selector sent to instance 0x10630fd80
2016-08-01 11:44:36.912 [5464:127765] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10630fd80
2016-08-01 11:44:36.914 [5464:127765] -[NSNull length]: unrecognized selector sent to instance 0x10630fd80
2016-08-01 11:44:36.914[5464:127765] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10630fd80
```

When i load the player i have this:

```
player.delegate = self

            player.addKPlayerEventListener("error", eventID: "error", handler: { (eventName, jsonString) in
                DLog("Error : \(eventName) :: \(jsonString)")
            })

            player.addKPlayerEventListener("timeupdate", eventID: "timeupdateVideoCard", handler: { (eventName, jsonString) in
                if let dictionary = jsonString.dictionaryFromJsonString() {
                    if let currentTime = dictionary["target"]?["currentTime"] as? Double, duration = dictionary["target"]?["duration"] as? Double {
                        // save a reference to the duration and progress
                        // this is used later when rotation happens and the progress bar needs to be restored to that position
                        self.videoDuration = duration
                        self.videoProgress = currentTime
                        self.videoPlayerDelegate?.onVideoProgressUpdate?(
                            currentTime:self.videoProgress,
                            duration: self.videoDuration,
                            animated: true)
                    }
                }
            })

            player.addKPlayerEventListener("onAddPlayerSpinner", eventID: "onAddPlayerSpinner", handler: { (eventName, jsonString:String?) in
                //  TODO: implement start spinner
                DLog("onAddPlayerSpinner")
                //self.showLoading()
            })

            player.addKPlayerEventListener("onRemovePlayerSpinner", eventID: "onRemovePlayerSpinner", handler: { (eventName, params:String?) in
                //self.hideLoading()
                DLog("onRemovePlayerSpinner")
            })

            let events = ["adClick","adErrorEvent","adsLoadError","AdSupport_EndAdPlayback","AdSupport_StartAdPlayback","midSequenceComplete","midSequenceStart","onAdComplete","onAdPlay","onAdSkip","postSequenceComplete","postSequenceStart","preSequenceComplete","preSequenceStart"]
            for event in events {
                DLog("player listening for event \(event)");
                player.addKPlayerEventListener(event, eventID:event, handler:{(eventName, jsonString) in
                    DLog("Event: \(eventName)")
                    DLog("Params: \(jsonString)")
                })
            }
```

None of these seem to catch the error and my player just sits there stuck. What to do?

**Comment by kaltura-hooks** [comment] 2016-08-01 10:09
Hi @piterwilson,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment] 2016-08-01 11:02
Hey @piterwilson,

Please try the following method:
https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPViewController.h#L34

this method supposed to reflect all errors on our player.

Let me know if it works for you.

Best,
Eliza

**Comment by piterwilson** [comment] 2016-08-01 11:33
You are referencing the` KPViewControllerDelegate` protocol

Yes we did set the delegate at the very top of the code snippet. Unfortunately the error doesn't appear in `func kPlayer(player: KPViewController!, didFailWithError error: NSError!) `

Other errors do surface there, just not this one. From your language it seems you have some doubt to whether this error should surface at all (you say: it's supposed to). Has anyone confirmed the `adsLoadError` error (KPIMAPlayerViewController line 176) actually does?

**Comment by ElizaSapir** [comment] 2016-08-01 12:02
@piterwilson  can you send me your config I want to try and reproduce this issue on my side.
When I ask for the config I mean:
serverUrl, partnerId, uiConfId, entryId

and if you attached plugins via KPPlayerConfig object send them too.

Thanks!

**Comment by piterwilson** [comment] 2016-08-01 12:30
How can i send you this information privately? Thanks.

**Comment by ElizaSapir** [comment] 2016-08-02 08:07
@piterwilson  I think it will be enough to share adTagUrl, send only this parameter.

Thanks!

**Comment by piterwilson** [comment] 2016-08-02 12:42
@ElizaSapir thanks. The adTagUrl is dynamic and returned by our client's server, here's one such instance

http://pubads.g.doubleclick.net/gampad/ads?env=vp&gdfp_req=1&impl=s&output=vast&unviewed_position_start=1&description_url=http%3A%2F%2Fdisneychannel.disney.co.uk&iu=/165891808/disney.co.uk/disneychannel/mobile-app/video/K.C.%20Undercover&sz=1920x480&url=[REFERRER_URL]&correlator=[TIMESTAMP]&ad_rule=1&cmsid=13728&ciu_szs=320x50,300x250&cust_params=appvsn%3D1.0.0%26country%3Duk%26disneycms%3Dtwc-app&vid=1_3yu051s1

**Comment by piterwilson** [comment] 2016-08-02 16:01
@ElizaSapir i can see that the url is returning an empty string, still, that error doesn't seem to surface to the native player, is that correct?

**Comment by ElizaSapir** [comment] 2016-08-02 19:27
Hey @piterwilson ,

Here is the way to get fired when you have this kind of error:

```
[_player addKPlayerEventListener:@"adErrorEvent" eventID:@"adErrorEvent" handler:^(NSString *eventName, NSString *params) {
                NSLog(@"error");
            }];
```

Looks like you already have a listener for this key, in my case it fired with your adTagUrl.

Please try to create specific listener not from array for this event `adErrorEvent` and let me know if it works for you.

Best,
Eliza

**Comment by piterwilson** [comment] 2016-08-03 07:47
@ElizaSapir thanks for your reply. I'm still not getting the events, but your example is not representative of my case because you are using objective c.

I am coding in swift and what i think it's happening is that the communication to swift is not implemented correctly. **Is that possible?** i remember that being the case in the previous version of the player where parameters that were marked as non null on the swift implementation were passed null values from objective c, making the calls fail. I'm not an expert on bridging from objective-c to swift, and there are so many delegate calls in between the original error and the player delegate, so i can't tell for sure.

That would explain all the null related errors though. 

`2016-08-03 09:32:12.419 Channel uk[1690:29760] ::Error:: -[KPIMAPlayerViewController adsLoader:failedWithErrorData:] (line:174) -- Error loading ads: Unable to request ads from server due to network error.
2016-08-03 09:32:12.521 Channel uk[1690:29760] -[NSNull length]: unrecognized selector sent to instance 0x10d920d80
2016-08-03 09:32:12.522  Channel uk[1690:29760] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10d920d80
2016-08-03 09:32:12.523 Channel uk[1690:29760] -[NSNull length]: unrecognized selector sent to instance 0x10d920d80
2016-08-03 09:32:12.524 Channel uk[1690:29760] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSInvalidArgumentException> -[NSNull length]: unrecognized selector sent to instance 0x10d920d80
`

**Comment by ElizaSapir** [comment] 2016-11-02 21:27
Closing due to inactivity

**Closed by ElizaSapir** 2016-11-02 21:27 UTC
Labels: question
