### ISSUE TITLE
Player gets wrong size when loading inline into a child of a child view controller

### ISSUE THREAD

**Issue by mikishab** [kaltura/player-sdk-native-ios#229] opened 2016-09-27 17:27 UTC
When loading the player into a view controller inline as in the docamentation:
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/Fullscreen-inline-iOS.html

We try to use this view controller as a child of another view controller and the player gets a wrong size until its fully loads.

After the player's Ready event is fired, when changing size (in our case rotating device) player works as expected.

A sample project where you can see the problem:
https://github.com/mikishab/KalturaDemoApp

**Comment by kaltura-hooks** [comment] 2016-09-27 17:35
Hi @mikishab,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by imrimarmor** [comment] 2016-10-25 10:17
28 days since the original issue was posted. Any thoughts?

**Comment by ElizaSapir** [comment] 2016-11-02 21:03
Hey @mikishab,

Please use the following doc:
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/Fullscreen-inline-iOS.html

the above doc explains how to create inline player.

Best,

Eliza

cc @itaykinnrot , @OrenMe

**Closed by ElizaSapir** 2016-11-02 21:03 UTC

**Comment by mikishab** [comment] 2016-11-08 10:06
Hi Eliza,

As I mentioned in my original post, i followed that same exact link:
https://vpaas.kaltura.com/documentation/Mobile-Video-Player-SDKs/Fullscreen-inline-iOS.html

As the link suggests here are the lines of code how we inline the Kaltura player.
https://github.com/mikishab/KalturaDemoApp/blob/master/KalturaDemo/VideoPlayer/TPKalturaPlayerController.m#L54
```
   self.player.view.frame = (CGRect){CGPointZero, self.view.frame.size};
   [self.player loadPlayerIntoViewController:self];
   [self.view addSubview:self.player.view];
```

Here is a video that demonstrate the problem, **although we followed the instruction**.
http://recordit.co/qhJXUFd5Ac

Please note: We are facing this issue with 3 levels of viewcontrollers -  a parent view controller ([TPVideoPlayerController.m](https://github.com/mikishab/KalturaDemoApp/blob/master/KalturaDemo/VideoPlayer/TPVideoPlayerController.m)) that contains a child viewcontroller ([TPKalturaPlayerController.m](https://github.com/mikishab/KalturaDemoApp/blob/master/KalturaDemo/VideoPlayer/TPKalturaPlayerController.m)) which inlines  the Kaltura player.

Can you suggest solution for the problem? 

Thanks,
Michael

**Comment by Njall2016** [comment] 2016-11-14 16:58
Hi, I couldn't reproduce issue with your demo. Please provide more information...

P.S. I've attached link to video with my test case: https://www.dropbox.com/s/py6xsyl9fp04uui/Player_gets_wrong_size%20.mov?dl=0.

**Comment by mikishab** [comment] 2016-11-15 08:22
@Njall2016 ,
Can you please record the same video with video screen opening on landscape or moving to landscape before video fully loaded (when spinner still sown) ?

**Comment by Njall2016** [comment] 2016-11-15 10:23
Yes of course. https://www.dropbox.com/s/v5v0yl6nu0376ad/moving_to_landscape_before%20video_fully_loaded.MOV?dl=0.
