### ISSUE TITLE
Play video programatically when it was paused

### ISSUE THREAD

**Issue by jonigl** [kaltura/player-sdk-native-ios#156] opened 2016-04-12 21:08 UTC
Hi,

I have this problem, when a video is playing and the player state is equal to KPMediaPlaybackStatePlaying suddenly it change to KPMediaPlaybackStatePaused and I don't know why this is happening. I suppose that is a connection problem. I need to keep playing the current video so I used the play method of the player, but this is not working for me, for some reason the player changed several times from KPMediaPlaybackStatePaused to KPMediaPlaybackStatePlaying and viceversa. I have to do a programmatically play because I need to use a chromeless player for restrictions of my project. 

This my code:

```
- (void)kPlayer:(KPViewController *)player playerPlaybackStateDidChange:(KPMediaPlaybackState)state{
    [self logPlaybackState: state];
    //if (state == KPMediaPlaybackStateEnded && counter < [entryIds count]-1){
    if (state == KPMediaPlaybackStateEnded && ![[Playlist thePlaylist] isLastEntrie]){
        //counter = counter + 1;
        NSLog(@"NEXT VIDEO");
        [[Playlist thePlaylist] nextEntrie];
        [player changeMedia:[[Playlist thePlaylist] getCurrentEntrieID]];
        //[player changeMedia:[entryIds[counter]objectForKey:@"id"]];
    }
    if (state == KPMediaPlaybackStatePaused && ![[Playlist thePlaylist] isLastEntrie]){
       [player.playerController play];
    }
    
}

```
Any ideas to getting this work? Any help would be very appreciate! Thanks in advance!

Best!
Jonathan

**Comment by kaltura-hooks** [comment] 2016-04-12 21:35
Hi @jonigl,

Thank for you reporting an issue and helping to improve Kaltura!

If you're having some issues getting your player set up, there are quite a few steps that can be taken to figure things out. 


In order to expedite the reporting process, please follow instructions in the doc below, prior to submitting a bug/issue

https://github.com/kaltura/player-sdk-native-ios/wiki/How-To-Report-an-Issue-with-the-Kaltura-iOS-Player-SDK


If you only have a general question rather than a bug report, please close this issue, post at:
https://forum.kaltura.org/c/community-forums/player-sdk

And add a comment to the Github issue linking to your post.

Thank you in advance!

**Comment by ElizaSapir** [comment] 2016-04-13 07:45
Hey @jonigl ,

Can you send me your config object?
I mean the initialization + some entry ID? I want to try and reproduce it on my side.

Thanks!

**Comment by jonigl** [comment] 2016-04-13 15:39
Hey @ElizaSapir how are you?

I just created a repository with sample code so you can try to reproduce my error (https://github.com/jonigl/kaltura-player-sdk-native-ios-issue-156). 
If you test with the ios simulator it should be stuck in KPMediaPlaybackStatePaused state. 

This is my output:

`2016-04-13 12:16:36.609 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER CONFIGURED
2016-04-13 12:16:36.728 kaltura-player-sdk-native-ios-issue#156[18385:2822553] NSRect: {{0, 0}, {375, 667}}
2016-04-13 12:16:36.739 kaltura-player-sdk-native-ios-issue#156[18385:2822553] HTTP:: http://vodgc.com/p/109/sp/10900/embedIframeJs/uiconf_id/23448994/entry_id/0_fms0o85z?wid=_109&uiconf_id=23448994&entry_id=0_fms0o85z&flashvars%5BloadingSpinner.plugin%5D=false&flashvars%5BEmbedPlayer.HidePosterOnStart%5D=true&flashvars%5BautoPlay%5D=true&flashvars%5BcontrolBarContainer.plugin%5D=false&flashvars%5BtopBarContainer.plugin%5D=false&flashvars%5BlargePlayBtn.plugin%5D=false&iframeembed=true#localContentId=&nativeSdkDrmFormats=&nativeSdkAllFormats=hls,mp4
2016-04-13 12:16:36.776 kaltura-player-sdk-native-ios-issue#156[18385:2822553] HTTP:: http://vodgc.com/html5/html5lib/v2.40/mwEmbedFrame.php/p/109/uiconf_id/23448994/entry_id/0_fms0o85z?wid=_109&wid=_109&uiconf_id=23448994&entry_id=0_fms0o85z&flashvars%5BloadingSpinner.plugin%5D=false&flashvars%5BEmbedPlayer.HidePosterOnStart%5D=true&flashvars%5BautoPlay%5D=true&flashvars%5BcontrolBarContainer.plugin%5D=false&flashvars%5BtopBarContainer.plugin%5D=false&flashvars%5BlargePlayBtn.plugin%5D=false&iframeembed=true#localContentId=&nativeSdkDrmFormats=&nativeSdkAllFormats=hls,mp4
2016-04-13 12:16:37.182 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:37.182 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePaused
2016-04-13 12:16:37.261 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:37.261 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePlaying
2016-04-13 12:16:43.473 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:43.474 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePaused
2016-04-13 12:16:43.477 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:43.477 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStateEnded
2016-04-13 12:16:43.478 kaltura-player-sdk-native-ios-issue#156[18385:2822553] NEXT VIDEO
2016-04-13 12:16:44.057 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:44.057 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePlaying
2016-04-13 12:16:44.061 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:44.061 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePaused
2016-04-13 12:16:44.065 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:44.065 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePlaying
2016-04-13 12:16:44.071 kaltura-player-sdk-native-ios-issue#156[18385:2822553] PLAYER PLAYBACK STATE DID CHANGE TO:
2016-04-13 12:16:44.071 kaltura-player-sdk-native-ios-issue#156[18385:2822553] KPMediaPlaybackStatePaused
`
Once in KPMediaPlaybackStatePaused it remains in it. Also I don't know why is in the output two HTTP:: logs. Are there two requests? or maybe something is wrong with my application.

Thanks in advance!

Best!

Jonathan

**Comment by ElizaSapir** [comment] 2016-04-13 19:36
Hey @jonigl ,

Looks like you are using an old version of our HTML5 player (kWidget: Kaltura HTML5 Version: 2.40)
please update to 2.42 and let me know if it works for you.

Thanks!

**Comment by jonigl** [comment] 2016-04-13 21:25
Hi @ElizaSapir ,

I changed from kaltura on prem to kaltura sass only for this tests, now I'm using kwidget version 2.42. But it is working worse than before because now the second video is not starting automatically (no autoplay for this video). And if I use the play method when KPMediaPlaybackStatePaused is detected, again for some reason the player changed several times from KPMediaPlaybackStatePaused to KPMediaPlaybackStatePlaying and viceversa. 

You can check it out on this repository: https://github.com/jonigl/kaltura-player-sdk-native-ios-issue-156 (I committed the latest changes on it).

Thanks in advance! :)

Best!

Jonathan

**Comment by ElizaSapir** [comment] 2016-04-14 11:18
Hey @jonigl ,

Can you try just for test using the following rc version:
http://kgit.html5video.org/tags/v2.43.rc2/mwEmbedFrame.php

Let me know if it works!

**Comment by jonigl** [comment] 2016-04-14 18:59
Hi @ElizaSapir 

I can't test this version because I don't have access to the Kaltura on prem implementation in order to make this change and also it's in production.

Perhaps I have to change something at the iOS SDK but honestly I don't know what I should modify to getting this work.

Could you guide me? and maybe that way I can do the test. 

Thanks! :)

Best!

Jonathan

**Comment by jonigl** [comment] 2016-04-14 20:05
I just want to add that autoplay seems that it's not working anymore in version 2.42. I'm using:

`[config addConfigKey:@"autoPlay" withValue:@"true"];`

I thing this config overwrite the KMC Studio Configuration of the player. I'm right?

Thanks!

**Comment by jonigl** [comment] 2016-04-15 01:13
Hi @ElizaSapir please look at this example, is another way to get the error:

```
[_player addKPlayerEventListener:@"playbackComplete" eventID:@"idPlaybackComplete" handler: ^(NSString *eventName , NSString *params){
        NSLog(@"player playback complete event listener");
        NSLog(@"NEXT VIDEO");
        playlistIndex++;
        [_player changeMedia:playlist[playlistIndex]];
    }];
[_player addKPlayerEventListener:@"playerReady" eventID:@"idPlayerReady" handler: ^(NSString *eventName , NSString *params){
        NSLog(@"player ready event listener");
        NSLog(@"PLAY");
        [_player.playerController play];
    }];
```

If you try to do this you get this output:

```
2016-04-14 22:08:06.165 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player ready event listener
2016-04-14 22:08:06.165 kaltura-player-sdk-native-ios-issue#156[43949:7104619] PLAY
2016-04-14 22:08:13.012 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:14.474 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:16.093 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player ready event listener
2016-04-14 22:08:16.093 kaltura-player-sdk-native-ios-issue#156[43949:7104619] PLAY
2016-04-14 22:08:16.143 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:16.999 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:17.011 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:17.790 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:17.818 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:18.410 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:18.450 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:18.927 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:18.941 kaltura-player-sdk-native-ios-issue#156[43949:7105004] 22:08:18.941 ERROR:    181: timed out after 0.012s (654 655); mMajorChangePending=0
2016-04-14 22:08:18.968 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:19.603 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:19.617 kaltura-player-sdk-native-ios-issue#156[43949:7105004] 22:08:19.617 ERROR:    181: timed out after 0.012s (656 657); mMajorChangePending=0
2016-04-14 22:08:19.636 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:20.206 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:20.247 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:20.707 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:20.708 kaltura-player-sdk-native-ios-issue#156[43949:7104619] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayI objectAtIndex:]: index 8 beyond bounds [0 .. 7]
2016-04-14 22:08:20.720 kaltura-player-sdk-native-ios-issue#156[43949:7105013] 22:08:20.720 ERROR:    181: timed out after 0.012s (663 664); mMajorChangePending=0
2016-04-14 22:08:20.745 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:21.247 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:21.247 kaltura-player-sdk-native-ios-issue#156[43949:7104619] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayI objectAtIndex:]: index 9 beyond bounds [0 .. 7]
2016-04-14 22:08:21.260 kaltura-player-sdk-native-ios-issue#156[43949:7106416] 22:08:21.260 ERROR:    181: timed out after 0.012s (667 667); mMajorChangePending=0
2016-04-14 22:08:21.332 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player playback complete event listener
2016-04-14 22:08:21.749 kaltura-player-sdk-native-ios-issue#156[43949:7104619] NEXT VIDEO
2016-04-14 22:08:21.749 kaltura-player-sdk-native-ios-issue#156[43949:7104619] *** WebKit discarded an uncaught exception in the webView:decidePolicyForNavigationAction:request:frame:decisionListener: delegate: <NSRangeException> *** -[__NSArrayI objectAtIndex:]: index 10 beyond bounds [0 .. 7]
2016-04-14 22:08:22.367 kaltura-player-sdk-native-ios-issue#156[43949:7104619] player ready event listener
2016-04-14 22:08:22.367 kaltura-player-sdk-native-ios-issue#156[43949:7104619] PLAY

```

If you debug this, you will notice that every time  changeMedia method is executed the  "playbackComplete" is called. It is like it would be stuck at this event... Pretty strange. 

Thank you for your assistance :)

Best!
Jonathan

**Comment by jonigl** [comment] 2016-04-25 16:20
Hi @ElizaSapir,

Any ideas about this issue?

Thanks!

**Comment by ElizaSapir** [comment] 2016-04-26 04:13
Hey @jonigl,

To know if the player is ready please use:
https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPViewController.h#L161

About "playbackComplete" please use the following delegate method:
https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPViewController.h#L30

and use the following state:
https://github.com/kaltura/player-sdk-native-ios/blob/master/KALTURAPlayerSDK/KPController.h#L24

Let me know if it resolves your issue.

Thanks!

**Comment by jonigl** [comment] 2016-05-09 15:47
Thanks @ElizaSapir! 

I used a different approach to solve this and worked perfect for me!

Sorry for my late answer in this issue.

Regards,
Jonathan

**Closed** 2016-05-24 15:55 UTC
